source ~/.vim/options.vim

call plug#begin() " plugins

Plug 'bluz71/vim-moonfly-colors', { 'as': 'moonfly' } " color scheme
Plug 'itchyny/lightline.vim' " lightline at the bottom
Plug 'tpope/vim-sensible'
Plug 'editorconfig/editorconfig-vim'
Plug 'tpope/vim-commentary'

" LSP stuff
Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
" END LSP stuff

call plug#end() " END plugins

colorscheme moonfly

set mouse=a
set list
set listchars=tab:▸\ ,trail:·,space:· " show boundary space
highlight SpecialKey ctermfg=darkgray guifg=#272727 " boundary space color

set timeoutlen=1000 ttimeoutlen=0

" lightline config
set laststatus=2
set noshowmode
" END lightline config

" Comment with CTRL+/
nnoremap <C-_> :Commentary<CR>
vnoremap <C-_> :Commentary<CR>
