source ~/.vim/options.vim

call plug#begin()

Plug 'bluz71/vim-moonfly-colors', { 'as': 'moonfly' } " Color scheme
Plug 'itchyny/lightline.vim' " Lightline at the bottom
Plug 'tpope/vim-sensible'

call plug#end()

colorscheme moonfly

set mouse=a
set list
set listchars=tab:▸\ ,trail:·,space:· " show boundary space
highlight SpecialKey ctermfg=darkgray guifg=#4e4e4e " boundary space color

set timeoutlen=1000 ttimeoutlen=0

" lightline config
set laststatus=2
set noshowmode
" END lightline config

