[main]
include = "~/.config/fuzzel/colors.ini"

font = Adwaita Sans:weight=medium:size=11
prompt = ""
placeholder = "Search for an application"

line-height = 16

horizontal-pad = 16
vertical-pad = 16

# Padding between input and match list
inner-pad = 8

lines = 8

width = 48

dpi-aware = auto

terminal = foot

[border]
width=2
radius=8
selection-radius=4
